### ISSUE TITLE
Exception while processing Similarity

### ISSUE THREAD

**Issue by JeffGoldner** [jonathanbrecher/sharedclustering#1]
**Describe the bug**
About 2 hours into processing my 177k Ancestry file, an exception was hit.

**To Reproduce**
Execute Similarity using default values

I can provide the txt file, too big to paste
[Data File](https://1drv.ms/t/s!AsO_d59wuLnNjrQQmFZsEGj9rWlsIg)

**Expected behavior**
Should complete

**Screenshots**
![image](https://user-images.githubusercontent.com/13804067/59276491-3c925100-8c13-11e9-83f2-1fc1bc40f680.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1903 Build 18362.145
 - Browser Not relevant 
 - Version 

**Smartphone (please complete the following information):**

**Additional context**
[SharedClusteringLog.txt](https://github.com/jonathanbrecher/sharedclustering/files/3276713/SharedClusteringLog.txt)

**Comment by jonathanbrecher** [comment]
Fixed in 1.1.0.44
