### ISSUE TITLE
Invalid username or password errors signing in to Ancestry

### ISSUE THREAD

**Issue by a1ch3mist** [jonathanbrecher/sharedclustering#2]
I went to the download tab, entered username & password and clicked Sign In. The first error message was Invalid Username or Password (it's not), and when retrying got other messages like saying an instance already running, and Unable to Sign In.

**Comment by jonathanbrecher** [comment]
I've never heard on an error about an instance already running. That doesn't sound like it's coming from Shared Clustering. Could you attach a screenshot of the full error message to this thread, or send it to sharedclustering@brechers.net?

**Comment by a1ch3mist** [comment]
Strange I went and started up the machine again and it worked OK this time. Maybe Ancestry's website was having an issue at the time I tried. I will close this ticket and re-open or open a new one if it happens again and I can take screenshots. Thanks for the great tool!
